from json import loads
from unittest import mock

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.test import TestCase
from ninja.testing import TestClient
from ninja_jwt.tokens import AccessToken
from parameterized import parameterized

from accounts.api import router

User = get_user_model()


class AccountRegistrationTestCase(TestCase):
    def setUp(self): ...
    def test_account_registration(self): ...
    def test_account_registration_username_already_exists(self): ...

    def test_account_registration_invalid_data_wrong_email(self): ...

    def test_account_registration_invalid_data_missing_keys(self): ...

    def test_account_registration_invalid_data_missing_root_key(self): ...

    def test_account_registration_invalid_data_empty_fields(self): ...


class AccountLoginTestCase(TestCase):
    def setUp(self): ...
    def test_account_login(self): ...
    def test_account_login_bad_password(self): ...
    def test_account_login_no_password(self): ...
    def test_account_login_invalid_data(self): ...


class UserViewTestCase(TestCase):
    def setUp(self): ...
    def test_user_view_get(self): ...
