name: Django CI test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install the latest version of uv
    - uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    #--------- Install required-version ---------
    - name:  Install required-version defined in uv.toml
      uses: astral-sh/setup-uv@v5
      with:
        pyproject-file: "pyproject.toml"

    #---- install root project -------
    - name: Run Test
      run: uv run pytest
